language: java
jdk:
  - openjdk8

branches: # (1)
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache: # (2)
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # (3)

before_deploy: # (1)
  - zip -r freelec-springboot2-webservice * # (2)
  - mkdir -p deploy # (3)
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip # (4)

deploy: # (5)
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: freelec-springboot-doop-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 # (6)
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications: # (4)
  email:
    recipients:
      - lch9502@naver.com